language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - compiler: clang
branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
script:
  - rake test
